//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace OM.Atman.Chakra.Plans.StrategyPlan {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl datePickerContentControl1;
        
        public Microsoft.Office.Tools.Word.PlainTextContentControl plainTextContentControl1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox1;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox2;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox3;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox4;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox5;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox6;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox7;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox8;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox9;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox10;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox11;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox12;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox13;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox14;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox20;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox21;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox22;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox23;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox24;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox25;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox26;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox27;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox28;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox29;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox30;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox31;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox32;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox33;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox34;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox35;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox36;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox37;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox38;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox39;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox40;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox41;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox42;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox43;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox44;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox45;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox46;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox47;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox48;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox49;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox50;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox51;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox52;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox53;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox54;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox55;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox56;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox57;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox58;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox59;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox60;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox61;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox62;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox63;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox64;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox67;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox66;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox65;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox68;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox69;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox70;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox71;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox72;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox73;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox74;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox75;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox76;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox77;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox78;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox79;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox80;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox81;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox82;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox83;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox84;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox85;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox86;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox87;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox88;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox89;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox90;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox91;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox92;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox93;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox94;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.datePickerContentControl1.BeginInit();
            this.plainTextContentControl1.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.plainTextContentControl1.EndInit();
            this.datePickerContentControl1.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.datePickerContentControl1 = Globals.Factory.CreateDatePickerContentControl(null, null, "1245073596", "datePickerContentControl1", this);
            this.plainTextContentControl1 = Globals.Factory.CreatePlainTextContentControl(null, null, "2347435309", "plainTextContentControl1", this);
            this.textBox1 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "0C79CD9540B7350475A0B1F70F164980E01F90", "0C79CD9540B7350475A0B1F70F164980E01F90", this, "textBox1");
            this.textBox2 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "189E73D801B5CC14D501947D1B9BDC4CA72591", "189E73D801B5CC14D501947D1B9BDC4CA72591", this, "textBox2");
            this.textBox3 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "2382DC2FA29A48245372A14B225237C42AF432", "2382DC2FA29A48245372A14B225237C42AF432", this, "textBox3");
            this.textBox4 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3CF8CA653373F934B4F38699388B3F5704B643", "3CF8CA653373F934B4F38699388B3F5704B643", this, "textBox4");
            this.textBox5 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "47EE0968F4ACFD4489649068473299ACBE5354", "47EE0968F4ACFD4489649068473299ACBE5354", this, "textBox5");
            this.textBox6 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "535AFA8485E0A85445B580CA5E9D1D003A30D5", "535AFA8485E0A85445B580CA5E9D1D003A30D5", this, "textBox6");
            this.textBox7 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "647CC0F7C631E5643BF6BC01655DB562E08626", "647CC0F7C631E5643BF6BC01655DB562E08626", this, "textBox7");
            this.textBox8 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7369C62C87130374F767866C723EB82CE14FC7", "7369C62C87130374F767866C723EB82CE14FC7", this, "textBox8");
            this.textBox9 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "81042A39B8A21A842528AEF28B3A56A8D7A498", "81042A39B8A21A842528AEF28B3A56A8D7A498", this, "textBox9");
            this.textBox10 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "98567F0F9953BD9441F99E5B9CCEEF705E0239", "98567F0F9953BD9441F99E5B9CCEEF705E0239", this, "textBox10");
            this.textBox11 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "151B956741C6021420518CC01E9451DD555431", "151B956741C6021420518CC01E9451DD555431", this, "textBox11");
            this.textBox12 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1EE44B3A911AD7140CF1BF521978AA5296D881", "1EE44B3A911AD7140CF1BF521978AA5296D881", this, "textBox12");
            this.textBox13 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1AB63A120161171425F1B9C7164631957EF261", "1AB63A120161171425F1B9C7164631957EF261", this, "textBox13");
            this.textBox14 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1FC8649A616E7C14C171A1BE1F7CAAF2E25761", "1FC8649A616E7C14C171A1BE1F7CAAF2E25761", this, "textBox14");
            this.textBox20 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1173E460D102561453D1882F1D866D83BD1841", "1173E460D102561453D1882F1D866D83BD1841", this, "textBox20");
            this.textBox21 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1CBFC3A4E19C59148A31B62E1ABF5BDA3009F1", "1CBFC3A4E19C59148A31B62E1ABF5BDA3009F1", this, "textBox21");
            this.textBox22 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "174F686C718A5514390182651BC43A7BC45D81", "174F686C718A5514390182651BC43A7BC45D81", this, "textBox22");
            this.textBox23 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "13FC42C2315711145F218D651FD5826F7A1F31", "13FC42C2315711145F218D651FD5826F7A1F31", this, "textBox23");
            this.textBox24 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1E3037F321471914D86188121CF105A4CC5F31", "1E3037F321471914D86188121CF105A4CC5F31", this, "textBox24");
            this.textBox25 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1D7A2A3D918791141451B7CA1970DBABB81BD1", "1D7A2A3D918791141451B7CA1970DBABB81BD1", this, "textBox25");
            this.textBox26 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "24ACAFEED2A94E24A8628A592AB16740573C52", "24ACAFEED2A94E24A8628A592AB16740573C52", this, "textBox26");
            this.textBox27 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "241CF58A42A20C240BF2B3BA215B0F0FD2B8C2", "241CF58A42A20C240BF2B3BA215B0F0FD2B8C2", this, "textBox27");
            this.textBox28 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "22DB8C7C92D5BF248382AE7C2802721EBF33C2", "22DB8C7C92D5BF248382AE7C2802721EBF33C2", this, "textBox28");
            this.textBox29 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "22E1445692D72C24783291D420412DF26DAB42", "22E1445692D72C24783291D420412DF26DAB42", this, "textBox29");
            this.textBox30 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "2B14A8D8A2CDD82481C284002A530CCBAE2E02", "2B14A8D8A2CDD82481C284002A530CCBAE2E02", this, "textBox30");
            this.textBox31 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "2C1F8CD5724AB424CAD2B82124452EFA279732", "2C1F8CD5724AB424CAD2B82124452EFA279732", this, "textBox31");
            this.textBox32 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "2714057152801124AC62A94B21B8C5CA152792", "2714057152801124AC62A94B21B8C5CA152792", this, "textBox32");
            this.textBox33 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "2FAEB2CBD28CD5240192B3B8224BF5040BBB22", "2FAEB2CBD28CD5240192B3B8224BF5040BBB22", this, "textBox33");
            this.textBox34 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "234471001220D824E222B1BC249F9BFADA5802", "234471001220D824E222B1BC249F9BFADA5802", this, "textBox34");
            this.textBox35 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "278FA4B9E2210624FD72B51326658A1FEDAA22", "278FA4B9E2210624FD72B51326658A1FEDAA22", this, "textBox35");
            this.textBox36 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "332875F503F3DD342D93B74C383CA11EF05CD3", "332875F503F3DD342D93B74C383CA11EF05CD3", this, "textBox36");
            this.textBox37 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3E3B636C73A19F34A32383DF3014F61DDA1A83", "3E3B636C73A19F34A32383DF3014F61DDA1A83", this, "textBox37");
            this.textBox38 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3B77876F33C36A347FA3B9FB3D01A35AFC7BD3", "3B77876F33C36A347FA3B9FB3D01A35AFC7BD3", this, "textBox38");
            this.textBox39 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3DB8CDEEC30A86347543A6053DF65134DC3673", "3DB8CDEEC30A86347543A6053DF65134DC3673", this, "textBox39");
            this.textBox40 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3872798083B6D634BD43973F33F3FD8AD98193", "3872798083B6D634BD43973F33F3FD8AD98193", this, "textBox40");
            this.textBox41 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "32C664F313F35634F1D3BC98348CBABC712D33", "32C664F313F35634F1D3BC98348CBABC712D33", this, "textBox41");
            this.textBox42 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "3F11F49FA323DE34B14396ED320688D75D25B3", "3F11F49FA323DE34B14396ED320688D75D25B3", this, "textBox42");
            this.textBox43 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "305D02BC93124D34D1B389603D669D9FDD4EB3", "305D02BC93124D34D1B389603D669D9FDD4EB3", this, "textBox43");
            this.textBox44 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "31B00E40D30252345993A73D307DFB503A2DA3", "31B00E40D30252345993A73D307DFB503A2DA3", this, "textBox44");
            this.textBox45 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "35E1F277F3493D341E3396FF3376648D41C653", "35E1F277F3493D341E3396FF3376648D41C653", this, "textBox45");
            this.textBox46 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4B4EB8ECD46367445E94AF3C4F6D7C10093484", "4B4EB8ECD46367445E94AF3C4F6D7C10093484", this, "textBox46");
            this.textBox47 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4BE245F5E4D3FD44DB64985046F89A5CADFAC4", "4BE245F5E4D3FD44DB64985046F89A5CADFAC4", this, "textBox47");
            this.textBox48 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "42AAB48214603344A71499CA41E600B0236944", "42AAB48214603344A71499CA41E600B0236944", this, "textBox48");
            this.textBox49 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4ECA89C9E45CB844F9949ED94B5341EBF37864", "4ECA89C9E45CB844F9949ED94B5341EBF37864", this, "textBox49");
            this.textBox50 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4984C2A8D44AEB4481D4918347B2AD8C055D44", "4984C2A8D44AEB4481D4918347B2AD8C055D44", this, "textBox50");
            this.textBox51 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "465D083E24A28A44B7A4BFB04062463E1850E4", "465D083E24A28A44B7A4BFB04062463E1850E4", this, "textBox51");
            this.textBox52 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4F2C5AFD64AEF64470949CDE4620E4BEF66FA4", "4F2C5AFD64AEF64470949CDE4620E4BEF66FA4", this, "textBox52");
            this.textBox53 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "47ECAB6F14CD874434A4B2D1440924087C7B44", "47ECAB6F14CD874434A4B2D1440924087C7B44", this, "textBox53");
            this.textBox54 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4986E71684CA1F447AC4A512475E21CFB10304", "4986E71684CA1F447AC4A512475E21CFB10304", this, "textBox54");
            this.textBox55 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "4157511E74F6A24489849CB7473338395663E4", "4157511E74F6A24489849CB7473338395663E4", this, "textBox55");
            this.textBox56 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5E124B32A5595154C10596445D231F83455FF5", "5E124B32A5595154C10596445D231F83455FF5", this, "textBox56");
            this.textBox57 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5A031BD7B5BCE45488D593155C22553B68C3E5", "5A031BD7B5BCE45488D593155C22553B68C3E5", this, "textBox57");
            this.textBox58 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5C99023655A7B054EC35AE795E28ECC3414D85", "5C99023655A7B054EC35AE795E28ECC3414D85", this, "textBox58");
            this.textBox59 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5409E40DD5D1EC542885A561505B9AF0F81D05", "5409E40DD5D1EC542885A561505B9AF0F81D05", this, "textBox59");
            this.textBox60 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5E69DBAA2550B654F225937F5E997C04430695", "5E69DBAA2550B654F225937F5E997C04430695", this, "textBox60");
            this.textBox61 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5BB1A0FE651DAD541BC5A6D054FAC2155025B5", "5BB1A0FE651DAD541BC5A6D054FAC2155025B5", this, "textBox61");
            this.textBox62 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "55782929A53C3854CC658900553D5098B35095", "55782929A53C3854CC658900553D5098B35095", this, "textBox62");
            this.textBox63 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "53519BBF852B9C546D85ACC256D12F582BBC45", "53519BBF852B9C546D85ACC256D12F582BBC45", this, "textBox63");
            this.textBox64 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "59EECC9535061654385595315265B66A37C145", "59EECC9535061654385595315265B66A37C145", this, "textBox64");
            this.textBox67 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "6CD1843F464F64640346A6CA696B38C96DA586", "6CD1843F464F64640346A6CA696B38C96DA586", this, "textBox67");
            this.textBox66 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "6AC0D6B506C22E64C776A9C46AAB3F3CC59486", "6AC0D6B506C22E64C776A9C46AAB3F3CC59486", this, "textBox66");
            this.textBox65 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5D6F49D7758C15541E45821858CA8488705A25", "5D6F49D7758C15541E45821858CA8488705A25", this, "textBox65");
            this.textBox68 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "6EB69B1C268BAE642406994566366349384316", "6EB69B1C268BAE642406994566366349384316", this, "textBox68");
            this.textBox69 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "62A9B77C162D1B64EE469CC563C0367C05BC86", "62A9B77C162D1B64EE469CC563C0367C05BC86", this, "textBox69");
            this.textBox70 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "6A63CB1506197564C3F6A793622BEE684B1126", "6A63CB1506197564C3F6A793622BEE684B1126", this, "textBox70");
            this.textBox71 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "6DA81C04060F9864A5B69D5E6637D63C7A71C6", "6DA81C04060F9864A5B69D5E6637D63C7A71C6", this, "textBox71");
            this.textBox72 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "617FDE4A46B16764D086B09765127E82349166", "617FDE4A46B16764D086B09765127E82349166", this, "textBox72");
            this.textBox73 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "620D7EB3566B86644D66823D6755CFDCE20546", "620D7EB3566B86644D66823D6755CFDCE20546", this, "textBox73");
            this.textBox74 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "63F4B07466DAFC642466AD626E8D54194CE6F6", "63F4B07466DAFC642466AD626E8D54194CE6F6", this, "textBox74");
            this.textBox75 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "663C9572A6C24D6435F6B7DF660A6721D43786", "663C9572A6C24D6435F6B7DF660A6721D43786", this, "textBox75");
            this.textBox76 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "73A80147F7171374F13798817A57CD30E54457", "73A80147F7171374F13798817A57CD30E54457", this, "textBox76");
            this.textBox77 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7118DAF6078DDC747FE7BC25768882C4D9BD17", "7118DAF6078DDC747FE7BC25768882C4D9BD17", this, "textBox77");
            this.textBox78 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7A5998BBF70B01743827A12971C958BBC55E67", "7A5998BBF70B01743827A12971C958BBC55E67", this, "textBox78");
            this.textBox79 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7E453EBB573CD674EA77AC77750FFD42EA7E07", "7E453EBB573CD674EA77AC77750FFD42EA7E07", this, "textBox79");
            this.textBox80 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "70ADA91947BC607498079C687F55EE93FB16C7", "70ADA91947BC607498079C687F55EE93FB16C7", this, "textBox80");
            this.textBox81 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7D8D6BF5C74EC47474378CAE795AF35D5A7B77", "7D8D6BF5C74EC47474378CAE795AF35D5A7B77", this, "textBox81");
            this.textBox82 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7C118CBE7708C87450879DC270B0643ECC4717", "7C118CBE7708C87450879DC270B0643ECC4717", this, "textBox82");
            this.textBox83 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "707BE5C797349D74E2B7A5B677B199B44C6127", "707BE5C797349D74E2B7A5B677B199B44C6127", this, "textBox83");
            this.textBox84 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "70BD0E68A776FF74B397BFBB795A9958698B17", "70BD0E68A776FF74B397BFBB795A9958698B17", this, "textBox84");
            this.textBox85 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "740D8844C7885C749C57B61A76FD4A950CB5B7", "740D8844C7885C749C57B61A76FD4A950CB5B7", this, "textBox85");
            this.textBox86 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "8F24D5B5584F8B840CF882FF85372844FD9D58", "8F24D5B5584F8B840CF882FF85372844FD9D58", this, "textBox86");
            this.textBox87 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "8C27A8BE8868498466D88CB188022B10A70ED8", "8C27A8BE8868498466D88CB188022B10A70ED8", this, "textBox87");
            this.textBox88 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "82FE5B7AD8761784531881F88C44645076FE08", "82FE5B7AD8761784531881F88C44645076FE08", this, "textBox88");
            this.textBox89 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "86AE1F12E8E3DE84003898F0891959E7BD0428", "86AE1F12E8E3DE84003898F0891959E7BD0428", this, "textBox89");
            this.textBox90 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "851A943898EE86840FD8A5748ECDD8F929B858", "851A943898EE86840FD8A5748ECDD8F929B858", this, "textBox90");
            this.textBox91 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "8E3D0E2708A64E84C978B07F8E324B22B321C8", "8E3D0E2708A64E84C978B07F8E324B22B321C8", this, "textBox91");
            this.textBox92 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "85F7A19D78972084C54887BB8FE424703E3A38", "85F7A19D78972084C54887BB8FE424703E3A38", this, "textBox92");
            this.textBox93 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "859552B888AB3D84E678AC4387A5C545C9C188", "859552B888AB3D84E678AC4387A5C545C9C188", this, "textBox93");
            this.textBox94 = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "8B20DD4DB873248459C8964D8C0EB23CA373C8", "8B20DD4DB873248459C8964D8C0EB23CA373C8", this, "textBox94");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // datePickerContentControl1
            // 
            this.datePickerContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // textBox1
            // 
            this.textBox1.BackColor = System.Drawing.Color.White;
            this.textBox1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox1.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.textBox1.Name = "textBox1";
            this.textBox1.Text = "+- 0.0 %";
            this.textBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox2
            // 
            this.textBox2.BackColor = System.Drawing.Color.White;
            this.textBox2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox2.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox2.Name = "textBox2";
            this.textBox2.Text = "+- 0.0 %";
            this.textBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox3
            // 
            this.textBox3.BackColor = System.Drawing.Color.White;
            this.textBox3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox3.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox3.Name = "textBox3";
            this.textBox3.Text = "0";
            this.textBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox4
            // 
            this.textBox4.BackColor = System.Drawing.Color.White;
            this.textBox4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox4.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox4.Name = "textBox4";
            this.textBox4.Text = "공격적 or 안정적";
            this.textBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox5
            // 
            this.textBox5.BackColor = System.Drawing.Color.White;
            this.textBox5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox5.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox5.Name = "textBox5";
            this.textBox5.Text = "약 00 일 정도 예상함";
            this.textBox5.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox6
            // 
            this.textBox6.BackColor = System.Drawing.Color.White;
            this.textBox6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox6.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox6.Name = "textBox6";
            this.textBox6.Text = "CL";
            this.textBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox7
            // 
            this.textBox7.BackColor = System.Drawing.Color.White;
            this.textBox7.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox7.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox7.Name = "textBox7";
            this.textBox7.Text = "해외선물";
            this.textBox7.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox8
            // 
            this.textBox8.BackColor = System.Drawing.Color.White;
            this.textBox8.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox8.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox8.Name = "textBox8";
            this.textBox8.Text = "0";
            this.textBox8.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox9
            // 
            this.textBox9.BackColor = System.Drawing.Color.White;
            this.textBox9.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox9.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox9.Name = "textBox9";
            this.textBox9.Text = "0";
            this.textBox9.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox10
            // 
            this.textBox10.BackColor = System.Drawing.Color.White;
            this.textBox10.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox10.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox10.Name = "textBox10";
            this.textBox10.Text = "0";
            this.textBox10.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox11
            // 
            this.textBox11.BackColor = System.Drawing.Color.White;
            this.textBox11.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox11.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox11.Name = "textBox11";
            this.textBox11.Text = "0";
            this.textBox11.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox12
            // 
            this.textBox12.BackColor = System.Drawing.Color.White;
            this.textBox12.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox12.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox12.Name = "textBox12";
            this.textBox12.Text = "0";
            this.textBox12.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox13
            // 
            this.textBox13.BackColor = System.Drawing.Color.White;
            this.textBox13.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox13.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox13.Name = "textBox13";
            this.textBox13.Text = "0";
            this.textBox13.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox14
            // 
            this.textBox14.BackColor = System.Drawing.Color.White;
            this.textBox14.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox14.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox14.Name = "textBox14";
            this.textBox14.Text = ".";
            // 
            // textBox20
            // 
            this.textBox20.BackColor = System.Drawing.Color.White;
            this.textBox20.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox20.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox20.Name = "textBox20";
            this.textBox20.Text = "0";
            this.textBox20.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox21
            // 
            this.textBox21.BackColor = System.Drawing.Color.White;
            this.textBox21.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox21.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox21.Name = "textBox21";
            this.textBox21.Text = ".";
            // 
            // textBox22
            // 
            this.textBox22.BackColor = System.Drawing.Color.White;
            this.textBox22.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox22.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox22.Name = "textBox22";
            this.textBox22.Text = ".";
            // 
            // textBox23
            // 
            this.textBox23.BackColor = System.Drawing.Color.White;
            this.textBox23.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox23.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox23.Name = "textBox23";
            this.textBox23.Text = ".";
            // 
            // textBox24
            // 
            this.textBox24.BackColor = System.Drawing.Color.White;
            this.textBox24.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox24.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox24.Name = "textBox24";
            this.textBox24.Text = ".";
            // 
            // textBox25
            // 
            this.textBox25.BackColor = System.Drawing.Color.White;
            this.textBox25.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox25.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox25.Name = "textBox25";
            this.textBox25.Text = ".";
            // 
            // textBox26
            // 
            this.textBox26.BackColor = System.Drawing.Color.White;
            this.textBox26.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox26.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox26.Name = "textBox26";
            this.textBox26.Text = "0";
            this.textBox26.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox27
            // 
            this.textBox27.BackColor = System.Drawing.Color.White;
            this.textBox27.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox27.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox27.Name = "textBox27";
            this.textBox27.Text = "0";
            this.textBox27.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox28
            // 
            this.textBox28.BackColor = System.Drawing.Color.White;
            this.textBox28.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox28.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox28.Name = "textBox28";
            this.textBox28.Text = "0";
            this.textBox28.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox29
            // 
            this.textBox29.BackColor = System.Drawing.Color.White;
            this.textBox29.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox29.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox29.Name = "textBox29";
            this.textBox29.Text = "상승or횡보or하락";
            this.textBox29.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox30
            // 
            this.textBox30.BackColor = System.Drawing.Color.White;
            this.textBox30.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox30.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox30.Name = "textBox30";
            this.textBox30.Text = "상승or횡보or하락";
            this.textBox30.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox31
            // 
            this.textBox31.BackColor = System.Drawing.Color.White;
            this.textBox31.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox31.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox31.Name = "textBox31";
            this.textBox31.Text = "상승or횡보or하락";
            this.textBox31.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox32
            // 
            this.textBox32.BackColor = System.Drawing.Color.White;
            this.textBox32.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox32.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox32.Name = "textBox32";
            this.textBox32.Text = "0";
            this.textBox32.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox33
            // 
            this.textBox33.BackColor = System.Drawing.Color.White;
            this.textBox33.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox33.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox33.Name = "textBox33";
            this.textBox33.Text = "0";
            this.textBox33.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox34
            // 
            this.textBox34.BackColor = System.Drawing.Color.White;
            this.textBox34.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox34.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox34.Name = "textBox34";
            this.textBox34.Text = "0";
            this.textBox34.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox35
            // 
            this.textBox35.BackColor = System.Drawing.Color.White;
            this.textBox35.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox35.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox35.Name = "textBox35";
            this.textBox35.Text = "0";
            this.textBox35.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox36
            // 
            this.textBox36.BackColor = System.Drawing.Color.White;
            this.textBox36.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox36.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox36.Name = "textBox36";
            this.textBox36.Text = "0";
            this.textBox36.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox37
            // 
            this.textBox37.BackColor = System.Drawing.Color.White;
            this.textBox37.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox37.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox37.Name = "textBox37";
            this.textBox37.Text = "0";
            this.textBox37.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox38
            // 
            this.textBox38.BackColor = System.Drawing.Color.White;
            this.textBox38.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox38.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox38.Name = "textBox38";
            this.textBox38.Text = "0";
            this.textBox38.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox39
            // 
            this.textBox39.BackColor = System.Drawing.Color.White;
            this.textBox39.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox39.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox39.Name = "textBox39";
            this.textBox39.Text = "0";
            this.textBox39.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox40
            // 
            this.textBox40.BackColor = System.Drawing.Color.White;
            this.textBox40.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox40.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox40.Name = "textBox40";
            this.textBox40.Text = "0";
            this.textBox40.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox41
            // 
            this.textBox41.BackColor = System.Drawing.Color.White;
            this.textBox41.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox41.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox41.Name = "textBox41";
            this.textBox41.Text = "0";
            this.textBox41.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox42
            // 
            this.textBox42.BackColor = System.Drawing.Color.White;
            this.textBox42.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox42.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox42.Name = "textBox42";
            this.textBox42.Text = "0";
            this.textBox42.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox43
            // 
            this.textBox43.BackColor = System.Drawing.Color.White;
            this.textBox43.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox43.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox43.Name = "textBox43";
            this.textBox43.Text = "0";
            this.textBox43.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox44
            // 
            this.textBox44.BackColor = System.Drawing.Color.White;
            this.textBox44.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox44.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox44.Name = "textBox44";
            this.textBox44.Text = "0";
            this.textBox44.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox45
            // 
            this.textBox45.BackColor = System.Drawing.Color.White;
            this.textBox45.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox45.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox45.Name = "textBox45";
            this.textBox45.Text = "0";
            this.textBox45.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox46
            // 
            this.textBox46.BackColor = System.Drawing.Color.White;
            this.textBox46.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox46.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox46.Name = "textBox46";
            this.textBox46.Text = "0";
            this.textBox46.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox47
            // 
            this.textBox47.BackColor = System.Drawing.Color.White;
            this.textBox47.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox47.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox47.Name = "textBox47";
            this.textBox47.Text = "0";
            this.textBox47.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox48
            // 
            this.textBox48.BackColor = System.Drawing.Color.White;
            this.textBox48.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox48.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox48.Name = "textBox48";
            this.textBox48.Text = "0";
            this.textBox48.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox49
            // 
            this.textBox49.BackColor = System.Drawing.Color.White;
            this.textBox49.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox49.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox49.Name = "textBox49";
            this.textBox49.Text = "0";
            this.textBox49.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox50
            // 
            this.textBox50.BackColor = System.Drawing.Color.White;
            this.textBox50.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox50.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox50.Name = "textBox50";
            this.textBox50.Text = "0";
            this.textBox50.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox51
            // 
            this.textBox51.BackColor = System.Drawing.Color.White;
            this.textBox51.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox51.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox51.Name = "textBox51";
            this.textBox51.Text = "0";
            this.textBox51.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox52
            // 
            this.textBox52.BackColor = System.Drawing.Color.White;
            this.textBox52.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox52.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox52.Name = "textBox52";
            this.textBox52.Text = "0";
            this.textBox52.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox53
            // 
            this.textBox53.BackColor = System.Drawing.Color.White;
            this.textBox53.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox53.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox53.Name = "textBox53";
            this.textBox53.Text = "0";
            this.textBox53.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox54
            // 
            this.textBox54.BackColor = System.Drawing.Color.White;
            this.textBox54.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox54.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox54.Name = "textBox54";
            this.textBox54.Text = "0";
            this.textBox54.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox55
            // 
            this.textBox55.BackColor = System.Drawing.Color.White;
            this.textBox55.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox55.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox55.Name = "textBox55";
            this.textBox55.Text = "0";
            this.textBox55.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox56
            // 
            this.textBox56.BackColor = System.Drawing.Color.White;
            this.textBox56.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox56.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox56.Name = "textBox56";
            this.textBox56.Text = "0";
            this.textBox56.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox57
            // 
            this.textBox57.BackColor = System.Drawing.Color.White;
            this.textBox57.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox57.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox57.Name = "textBox57";
            this.textBox57.Text = "0";
            this.textBox57.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox58
            // 
            this.textBox58.BackColor = System.Drawing.Color.White;
            this.textBox58.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox58.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox58.Name = "textBox58";
            this.textBox58.Text = "0";
            this.textBox58.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox59
            // 
            this.textBox59.BackColor = System.Drawing.Color.White;
            this.textBox59.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox59.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox59.Name = "textBox59";
            this.textBox59.Text = "0";
            this.textBox59.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox60
            // 
            this.textBox60.BackColor = System.Drawing.Color.White;
            this.textBox60.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox60.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox60.Name = "textBox60";
            this.textBox60.Text = "0";
            this.textBox60.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox61
            // 
            this.textBox61.BackColor = System.Drawing.Color.White;
            this.textBox61.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox61.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox61.Name = "textBox61";
            this.textBox61.Text = "0";
            this.textBox61.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox62
            // 
            this.textBox62.BackColor = System.Drawing.Color.White;
            this.textBox62.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox62.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox62.Name = "textBox62";
            this.textBox62.Text = "0";
            this.textBox62.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox63
            // 
            this.textBox63.BackColor = System.Drawing.Color.White;
            this.textBox63.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox63.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox63.Name = "textBox63";
            this.textBox63.Text = "0";
            this.textBox63.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox64
            // 
            this.textBox64.BackColor = System.Drawing.Color.White;
            this.textBox64.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox64.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox64.Name = "textBox64";
            this.textBox64.Text = "0";
            this.textBox64.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox67
            // 
            this.textBox67.BackColor = System.Drawing.Color.White;
            this.textBox67.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox67.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox67.Name = "textBox67";
            this.textBox67.Text = "0";
            this.textBox67.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox66
            // 
            this.textBox66.BackColor = System.Drawing.Color.White;
            this.textBox66.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox66.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox66.Name = "textBox66";
            this.textBox66.Text = "0";
            this.textBox66.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox65
            // 
            this.textBox65.BackColor = System.Drawing.Color.White;
            this.textBox65.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox65.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox65.Name = "textBox65";
            this.textBox65.Text = "0";
            this.textBox65.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox68
            // 
            this.textBox68.BackColor = System.Drawing.Color.White;
            this.textBox68.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox68.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox68.Name = "textBox68";
            this.textBox68.Text = ".";
            // 
            // textBox69
            // 
            this.textBox69.BackColor = System.Drawing.Color.White;
            this.textBox69.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox69.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox69.Name = "textBox69";
            this.textBox69.Text = ".";
            // 
            // textBox70
            // 
            this.textBox70.BackColor = System.Drawing.Color.White;
            this.textBox70.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox70.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox70.Name = "textBox70";
            this.textBox70.Text = ".";
            // 
            // textBox71
            // 
            this.textBox71.BackColor = System.Drawing.Color.White;
            this.textBox71.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox71.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox71.Name = "textBox71";
            this.textBox71.Text = ".";
            // 
            // textBox72
            // 
            this.textBox72.BackColor = System.Drawing.Color.White;
            this.textBox72.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox72.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox72.Name = "textBox72";
            this.textBox72.Text = "0";
            this.textBox72.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox73
            // 
            this.textBox73.BackColor = System.Drawing.Color.White;
            this.textBox73.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox73.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox73.Name = "textBox73";
            this.textBox73.Text = ".";
            // 
            // textBox74
            // 
            this.textBox74.BackColor = System.Drawing.Color.White;
            this.textBox74.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox74.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox74.Name = "textBox74";
            this.textBox74.Text = "0";
            this.textBox74.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox75
            // 
            this.textBox75.BackColor = System.Drawing.Color.White;
            this.textBox75.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox75.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox75.Name = "textBox75";
            this.textBox75.Text = ".";
            // 
            // textBox76
            // 
            this.textBox76.BackColor = System.Drawing.Color.White;
            this.textBox76.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox76.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox76.Name = "textBox76";
            this.textBox76.Text = "0";
            this.textBox76.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox77
            // 
            this.textBox77.BackColor = System.Drawing.Color.White;
            this.textBox77.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox77.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox77.Name = "textBox77";
            this.textBox77.Text = ".";
            // 
            // textBox78
            // 
            this.textBox78.BackColor = System.Drawing.Color.White;
            this.textBox78.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox78.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox78.Name = "textBox78";
            this.textBox78.Text = "0";
            this.textBox78.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox79
            // 
            this.textBox79.BackColor = System.Drawing.Color.White;
            this.textBox79.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox79.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox79.Name = "textBox79";
            this.textBox79.Text = ".";
            // 
            // textBox80
            // 
            this.textBox80.BackColor = System.Drawing.Color.White;
            this.textBox80.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox80.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox80.Name = "textBox80";
            this.textBox80.Text = "0";
            this.textBox80.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox81
            // 
            this.textBox81.BackColor = System.Drawing.Color.White;
            this.textBox81.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox81.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox81.Name = "textBox81";
            this.textBox81.Text = ".";
            // 
            // textBox82
            // 
            this.textBox82.BackColor = System.Drawing.Color.White;
            this.textBox82.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox82.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox82.Name = "textBox82";
            this.textBox82.Text = "0";
            this.textBox82.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox83
            // 
            this.textBox83.BackColor = System.Drawing.Color.White;
            this.textBox83.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox83.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox83.Name = "textBox83";
            this.textBox83.Text = ".";
            // 
            // textBox84
            // 
            this.textBox84.BackColor = System.Drawing.Color.White;
            this.textBox84.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox84.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox84.Name = "textBox84";
            this.textBox84.Text = "0";
            this.textBox84.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox85
            // 
            this.textBox85.BackColor = System.Drawing.Color.White;
            this.textBox85.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox85.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox85.Name = "textBox85";
            this.textBox85.Text = ".";
            // 
            // textBox86
            // 
            this.textBox86.BackColor = System.Drawing.Color.White;
            this.textBox86.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox86.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox86.Name = "textBox86";
            this.textBox86.Text = "0";
            this.textBox86.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox87
            // 
            this.textBox87.BackColor = System.Drawing.Color.White;
            this.textBox87.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox87.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox87.Name = "textBox87";
            this.textBox87.Text = ".";
            // 
            // textBox88
            // 
            this.textBox88.BackColor = System.Drawing.Color.White;
            this.textBox88.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox88.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox88.Name = "textBox88";
            this.textBox88.Text = "0";
            this.textBox88.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox89
            // 
            this.textBox89.BackColor = System.Drawing.Color.White;
            this.textBox89.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox89.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox89.Name = "textBox89";
            this.textBox89.Text = ".";
            // 
            // textBox90
            // 
            this.textBox90.BackColor = System.Drawing.Color.White;
            this.textBox90.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox90.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox90.Name = "textBox90";
            this.textBox90.Text = "0";
            this.textBox90.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox91
            // 
            this.textBox91.BackColor = System.Drawing.Color.White;
            this.textBox91.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox91.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox91.Name = "textBox91";
            this.textBox91.Text = ".";
            // 
            // textBox92
            // 
            this.textBox92.BackColor = System.Drawing.Color.White;
            this.textBox92.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox92.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox92.Name = "textBox92";
            this.textBox92.Text = "0";
            this.textBox92.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // textBox93
            // 
            this.textBox93.BackColor = System.Drawing.Color.White;
            this.textBox93.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox93.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox93.Name = "textBox93";
            this.textBox93.Text = ".";
            // 
            // textBox94
            // 
            this.textBox94.BackColor = System.Drawing.Color.White;
            this.textBox94.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox94.Font = new System.Drawing.Font("굴림", 11F, System.Drawing.FontStyle.Bold);
            this.textBox94.Name = "textBox94";
            this.textBox94.Text = "0";
            this.textBox94.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // plainTextContentControl1
            // 
            this.plainTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
            this.textBox1.BindingContext = this.BindingContext;
            this.textBox2.BindingContext = this.BindingContext;
            this.textBox3.BindingContext = this.BindingContext;
            this.textBox4.BindingContext = this.BindingContext;
            this.textBox5.BindingContext = this.BindingContext;
            this.textBox6.BindingContext = this.BindingContext;
            this.textBox7.BindingContext = this.BindingContext;
            this.textBox8.BindingContext = this.BindingContext;
            this.textBox9.BindingContext = this.BindingContext;
            this.textBox10.BindingContext = this.BindingContext;
            this.textBox11.BindingContext = this.BindingContext;
            this.textBox12.BindingContext = this.BindingContext;
            this.textBox13.BindingContext = this.BindingContext;
            this.textBox14.BindingContext = this.BindingContext;
            this.textBox20.BindingContext = this.BindingContext;
            this.textBox21.BindingContext = this.BindingContext;
            this.textBox22.BindingContext = this.BindingContext;
            this.textBox23.BindingContext = this.BindingContext;
            this.textBox24.BindingContext = this.BindingContext;
            this.textBox25.BindingContext = this.BindingContext;
            this.textBox26.BindingContext = this.BindingContext;
            this.textBox27.BindingContext = this.BindingContext;
            this.textBox28.BindingContext = this.BindingContext;
            this.textBox29.BindingContext = this.BindingContext;
            this.textBox30.BindingContext = this.BindingContext;
            this.textBox31.BindingContext = this.BindingContext;
            this.textBox32.BindingContext = this.BindingContext;
            this.textBox33.BindingContext = this.BindingContext;
            this.textBox34.BindingContext = this.BindingContext;
            this.textBox35.BindingContext = this.BindingContext;
            this.textBox36.BindingContext = this.BindingContext;
            this.textBox37.BindingContext = this.BindingContext;
            this.textBox38.BindingContext = this.BindingContext;
            this.textBox39.BindingContext = this.BindingContext;
            this.textBox40.BindingContext = this.BindingContext;
            this.textBox41.BindingContext = this.BindingContext;
            this.textBox42.BindingContext = this.BindingContext;
            this.textBox43.BindingContext = this.BindingContext;
            this.textBox44.BindingContext = this.BindingContext;
            this.textBox45.BindingContext = this.BindingContext;
            this.textBox46.BindingContext = this.BindingContext;
            this.textBox47.BindingContext = this.BindingContext;
            this.textBox48.BindingContext = this.BindingContext;
            this.textBox49.BindingContext = this.BindingContext;
            this.textBox50.BindingContext = this.BindingContext;
            this.textBox51.BindingContext = this.BindingContext;
            this.textBox52.BindingContext = this.BindingContext;
            this.textBox53.BindingContext = this.BindingContext;
            this.textBox54.BindingContext = this.BindingContext;
            this.textBox55.BindingContext = this.BindingContext;
            this.textBox56.BindingContext = this.BindingContext;
            this.textBox57.BindingContext = this.BindingContext;
            this.textBox58.BindingContext = this.BindingContext;
            this.textBox59.BindingContext = this.BindingContext;
            this.textBox60.BindingContext = this.BindingContext;
            this.textBox61.BindingContext = this.BindingContext;
            this.textBox62.BindingContext = this.BindingContext;
            this.textBox63.BindingContext = this.BindingContext;
            this.textBox64.BindingContext = this.BindingContext;
            this.textBox67.BindingContext = this.BindingContext;
            this.textBox66.BindingContext = this.BindingContext;
            this.textBox65.BindingContext = this.BindingContext;
            this.textBox68.BindingContext = this.BindingContext;
            this.textBox69.BindingContext = this.BindingContext;
            this.textBox70.BindingContext = this.BindingContext;
            this.textBox71.BindingContext = this.BindingContext;
            this.textBox72.BindingContext = this.BindingContext;
            this.textBox73.BindingContext = this.BindingContext;
            this.textBox74.BindingContext = this.BindingContext;
            this.textBox75.BindingContext = this.BindingContext;
            this.textBox76.BindingContext = this.BindingContext;
            this.textBox77.BindingContext = this.BindingContext;
            this.textBox78.BindingContext = this.BindingContext;
            this.textBox79.BindingContext = this.BindingContext;
            this.textBox80.BindingContext = this.BindingContext;
            this.textBox81.BindingContext = this.BindingContext;
            this.textBox82.BindingContext = this.BindingContext;
            this.textBox83.BindingContext = this.BindingContext;
            this.textBox84.BindingContext = this.BindingContext;
            this.textBox85.BindingContext = this.BindingContext;
            this.textBox86.BindingContext = this.BindingContext;
            this.textBox87.BindingContext = this.BindingContext;
            this.textBox88.BindingContext = this.BindingContext;
            this.textBox89.BindingContext = this.BindingContext;
            this.textBox90.BindingContext = this.BindingContext;
            this.textBox91.BindingContext = this.BindingContext;
            this.textBox92.BindingContext = this.BindingContext;
            this.textBox93.BindingContext = this.BindingContext;
            this.textBox94.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.plainTextContentControl1.Dispose();
            this.datePickerContentControl1.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
